# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20170531_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truefalsequestion',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
